from app.models.traffic_collisions import TrafficCollision
from app.models.collision_type import CollisionType
from app.models.severity import Severity
from app.models.sdot_collision_type import SDOTCollisionType
from app.models.junction_type import JunctionType
from app.models.light_condition import LightCondition
from app.models.weather_condition import WeatherCondition
from app.models.road_condition import RoadCondition
from app.models.address_type import AddressType